name: Test-Flow CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint Go Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
          cache: true

      - name: Print Go version
        run: go version

      - name: Verify go.mod tidiness
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=3m --fail-on-error ./...

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.7'
          cache: true

      - name: Print Go version
        run: go version

      - name: Check for tests
        run: |
          if [ -n "$(find . -name '*_test.go')" ]; then
            go test -v -coverprofile=coverage.out ./...
          else
            echo "No test files found. Skipping test step."
            exit 0
          fi

      - name: Upload coverage report
        if: always()  
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.out
          retention-days: 1

  build:
    name: Build CLI
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.7'
          cache: true

      - name: Print Go version
        run: go version

      - name: Build CLI
        run: |
          mkdir -p dist
          go build -o dist/testflow ./cmd/testflow # Adjust if main.go is in cmd/

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: testflow-binary
          path: dist/testflow
          retention-days: 1